# Generated by Django 3.0 on 2020-04-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_optimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.TextField()),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_optimization.Page')),
            ],
        ),
    ]
