# Generated by Django 3.0 on 2020-03-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(default='MALE', max_length=10),
        ),
    ]
